import type { PlaylistDefinition } from "./types";

export const CURATED_PLAYLISTS: PlaylistDefinition[] = [
  // ── Featured ──────────────────────────────────────────────
  {
    id: "night-vibes",
    name: "Night Vibes",
    description: "Late-night jazz, lounge, and chill",
    category: "featured",
    query: { tag: "jazz", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#3b82f6",
  },
  {
    id: "electronic-pulse",
    name: "Electronic Pulse",
    description: "Dance, house, trance, electronic",
    category: "featured",
    query: { tag: "electronic", tagExact: true, order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#8b5cf6",
  },
  {
    id: "world-beat",
    name: "World Beat",
    description: "Global folk and world music",
    category: "featured",
    query: { tag: "world music", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#22c55e",
  },
  {
    id: "classical-hour",
    name: "Classical Hour",
    description: "Orchestral and chamber music",
    category: "featured",
    query: { tag: "classical", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#f59e0b",
  },
  {
    id: "retro-wave",
    name: "Retro Wave",
    description: "70s, 80s, 90s hits and oldies",
    category: "featured",
    query: { tagList: "80s,oldies", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#f97316",
  },
  {
    id: "latin-heat",
    name: "Latin Heat",
    description: "Latin, sertanejo, regional Mexican",
    category: "featured",
    query: { tag: "latin", tagExact: true, order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#e11d48",
  },

  // ── Mood & Activity ───────────────────────────────────────
  {
    id: "study-session",
    name: "Study Session",
    description: "Lo-fi, chillout, and ambient focus",
    category: "mood",
    query: { tagList: "lofi,chillout,ambient", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#14b8a6",
  },
  {
    id: "road-trip",
    name: "Road Trip",
    description: "Rock, country, and classic sing-alongs",
    category: "mood",
    query: { tagList: "rock,classic rock,country", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#ef4444",
  },
  {
    id: "party-mix",
    name: "Party Mix",
    description: "Dance, house, and pop hits",
    category: "mood",
    query: { tagList: "dance,house,pop", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#ec4899",
  },
  {
    id: "meditation",
    name: "Meditation",
    description: "Relaxation and mindfulness",
    category: "mood",
    query: { tagList: "meditation,relaxation", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#22d3ee",
  },
  {
    id: "workout-energy",
    name: "Workout Energy",
    description: "High-energy electronic and hip hop",
    category: "mood",
    query: { tagList: "electronic,dance,hip hop", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#f43f5e",
  },

  // ── Genres ────────────────────────────────────────────────
  {
    id: "indie-underground",
    name: "Indie Underground",
    description: "Alternative and indie stations",
    category: "genre",
    query: { tag: "alternative", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#ef4444",
  },
  {
    id: "hip-hop-central",
    name: "Hip Hop Central",
    description: "Hip hop, rap, and R&B",
    category: "genre",
    query: { tagList: "hip hop,rap,r&b", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#f43f5e",
  },
  {
    id: "rock-arena",
    name: "Rock Arena",
    description: "Rock, classic rock, and metal",
    category: "genre",
    query: { tagList: "rock,classic rock,metal", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#dc2626",
  },
  {
    id: "blues-and-soul",
    name: "Blues & Soul",
    description: "Blues, soul, and rhythm",
    category: "genre",
    query: { tagList: "blues,soul", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#2563eb",
  },
  {
    id: "reggae-island",
    name: "Reggae Island",
    description: "Reggae, dub, and island vibes",
    category: "genre",
    query: { tag: "reggae", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#16a34a",
  },
  {
    id: "punk-hardcore",
    name: "Punk & Hardcore",
    description: "Punk rock and hardcore",
    category: "genre",
    query: { tagList: "punk,hardcore", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#b91c1c",
  },
  {
    id: "kpop-jpop",
    name: "K-Pop & J-Pop",
    description: "Korean pop, J-pop, and anime",
    category: "genre",
    query: { tagList: "kpop,jpop,anime", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#ec4899",
  },
  {
    id: "ambient-space",
    name: "Ambient Space",
    description: "Ambient, drone, and experimental",
    category: "genre",
    query: { tagList: "ambient,drone,experimental", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#14b8a6",
  },

  // ── Regional & Language ───────────────────────────────────
  {
    id: "afrobeats",
    name: "Afrobeats",
    description: "Afrobeat and African music",
    category: "regional",
    query: { tagList: "afrobeat,african", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#ca8a04",
  },
  {
    id: "arabic-radio",
    name: "Arabic Radio",
    description: "Arabic music and talk",
    category: "regional",
    query: { language: "arabic", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#059669",
  },
  {
    id: "french-radio",
    name: "French Radio",
    description: "French music, pop, and chanson",
    category: "regional",
    query: { language: "french", order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#3b82f6",
  },
  {
    id: "hindi-radio",
    name: "Hindi Radio",
    description: "Bollywood, Hindi pop, and classics",
    category: "regional",
    query: { language: "hindi", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#f97316",
  },
  {
    id: "portuguese-vibes",
    name: "Portuguese Vibes",
    description: "Portuguese and Brazilian music",
    category: "regional",
    query: { language: "portuguese", order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#22c55e",
  },

  // ── Talk & More ───────────────────────────────────────────
  {
    id: "news-desk",
    name: "News Desk",
    description: "News and talk radio worldwide",
    category: "talk",
    query: { tag: "news", tagExact: true, order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#eab308",
  },
  {
    id: "sports-radio",
    name: "Sports Radio",
    description: "Live sports and sports talk",
    category: "talk",
    query: { tag: "sports", tagExact: true, order: "clickcount", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#22c55e",
  },
  {
    id: "christian-radio",
    name: "Christian Radio",
    description: "Christian music and worship",
    category: "talk",
    query: { tag: "christian", tagExact: true, order: "votes", reverse: true, limit: 100, hidebroken: true, bitrateMin: 64 },
    color: "#a855f7",
  },
];

export const PLAYLIST_CATEGORY_LABELS: Record<string, string> = {
  featured: "Featured",
  mood: "Mood & Activity",
  genre: "Genres",
  regional: "Regional & Language",
  talk: "Talk & More",
};

export const PLAYLIST_CATEGORY_ORDER = ["featured", "mood", "genre", "regional", "talk"] as const;
